### ISSUE TITLE
Host unable to move anything

### ISSUE THREAD

**Issue by FearlessNite345** [Fozkais/CMS21-Together#9]
So as the host i built and compiled this for my friend sent him the files he is able to move cars and put on an remove and i see all of it but for me (the host) i can not do any of that as it will not be synced with him and i don't understand why

**Comment by Fozkais** [comment]
first on on what version of the mod are you playing ? 
it's a strange issue but i've already seen it , you can try reload the game and hopefully it'll work but i cant help you more with that , if there is any error on console i would need the FULL log of your sesssion so i can see what happened :)

**Comment by FearlessNite345** [comment]
Playing on version 0.3.3 we tried reloading and even new saves but same kept happening very odd i didn't notice any errors i will say on my end my console was spamming "Received Bodypart" not sure if that's normal for the host or not
